[tool]

  [tool.isort]
    from_first = true
    line_length = 88
    profile = "black"

  [tool.black]
    line-length = 132

  [tool.coverage]

    [tool.coverage.report]
      exclude_lines = ["pragma: no cover", "raise NotImplementedError"]
      fail_under = 0
      ignore_errors = true
      show_missing = true

    [tool.coverage.run]
      branch = false
      omit = ["**/tests/**/*", "**/setup.py"]

  [tool.kedro]
    package_name = "popsign_meow"
    project_name = "popsign-meow"
    kedro_init_version = "0.18.6"

  [tool.mypy]
    cache_dir = "~/.cache/mypy"
    ignore_missing_imports = true

  [tool.pylint]

    [tool.pylint.master]
      jobs = 4

    [tool.pylint.basic]
      extension-pkg-whitelist = "lxml,mpi4py"

      argument-rgx  = "[_a-zA-Z][_a-zA-Z0-9]*"
      attr-rgx      = "[_a-zA-Z][_a-zA-Z0-9]*"
      const-rgx     = "[_a-zA-Z][_a-zA-Z0-9]*"
      function-rgx  = "[_a-zA-Z][_a-zA-Z0-9]*"
      method-rgx    = "[_a-zA-Z][_a-zA-Z0-9]*"
      variable-rgx  = "[_a-zA-Z][_a-zA-Z0-9]*"

    [tool.pylint.format]
      max-line-length = 132

    [tool.pylint.messages_control]
      disable = [
        "C0103",  # invalid-name
        "C0111",  # missing-module-docstring
        "C0209",  # consider-using-f-strings
        "C0302",  # too-many-lines
        "C0414",  # useless-import-alias
        "C3001",  # unnecessary-lamba-assignment
        "R0801",  # duplicate-code
        "R0901",  # too-many-ancestors
        "R0902",  # too-many-instance-attributes
        "R0903",  # too-few-public-methods
        "R0904",  # too-many-public-methods
        "R0911",  # too-many-return-statements
        "R0912",  # too-many-branches
        "R0913",  # too-many-arguments
        "R0914",  # too-many-locals
        "R0915",  # too-many-statements
        "R0916",  # too-many-boolean-expressions
        "R1702",  # too-many-nested-blocks
        "W0107",  # unnecessary-pass
        "W0511",  # fixme
        "W0603",  # global-statement
      ]

    [tool.pylint.miscellaneous]
      notes = ""

    [tool.pylint.reports]
      score = false

    [tool.pylint.similarities]
      ignore-imports = true

  [tool.pytest]

    [tool.pytest.ini_options]
      filterwarnings = ["ignore::DeprecationWarning"]
      addopts = "--cov-report term-missing --cov src/popsign_meow -ra"